name: CI

on: [push]

jobs:
 sast_scan:
  name: Run le scan Bandit
  runs-on: ubuntu-latest

  steps:
  - name: Checkout out
    uses: actions/checkout@v2

  - name: set Python
    uses: actions/setup-python@v2
    with:
      python-version: 3.8

  - name: Install Bandit
    run: pip install bandit

  - name: Run Bandit Scan
    run: bandit -r . -ll -f json -o bandit_report.json

  - name: Bandit report
    uses: actions/upload-artifact@v7.0.1
    path: bandit_report.json
    
  
